application: mailmyresult
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /main/favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /main/.*
  script: main.app

- url: /.*
  script: main.app



libraries:
- name: webapp2
  version: "2.5.2"
